// Generated by gencpp from file laba2/WECRequest.msg
// DO NOT EDIT!


#ifndef LABA2_MESSAGE_WECREQUEST_H
#define LABA2_MESSAGE_WECREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laba2
{
template <class ContainerAllocator>
struct WECRequest_
{
  typedef WECRequest_<ContainerAllocator> Type;

  WECRequest_()
    : country()  {
    }
  WECRequest_(const ContainerAllocator& _alloc)
    : country(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _country_type;
  _country_type country;





  typedef boost::shared_ptr< ::laba2::WECRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laba2::WECRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WECRequest_

typedef ::laba2::WECRequest_<std::allocator<void> > WECRequest;

typedef boost::shared_ptr< ::laba2::WECRequest > WECRequestPtr;
typedef boost::shared_ptr< ::laba2::WECRequest const> WECRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laba2::WECRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laba2::WECRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laba2::WECRequest_<ContainerAllocator1> & lhs, const ::laba2::WECRequest_<ContainerAllocator2> & rhs)
{
  return lhs.country == rhs.country;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laba2::WECRequest_<ContainerAllocator1> & lhs, const ::laba2::WECRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laba2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::laba2::WECRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laba2::WECRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laba2::WECRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laba2::WECRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laba2::WECRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laba2::WECRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laba2::WECRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b881e0d67de40e25f0c6b55bc3f6e9ed";
  }

  static const char* value(const ::laba2::WECRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb881e0d67de40e25ULL;
  static const uint64_t static_value2 = 0xf0c6b55bc3f6e9edULL;
};

template<class ContainerAllocator>
struct DataType< ::laba2::WECRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laba2/WECRequest";
  }

  static const char* value(const ::laba2::WECRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laba2::WECRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string country\n"
;
  }

  static const char* value(const ::laba2::WECRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laba2::WECRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.country);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WECRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laba2::WECRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laba2::WECRequest_<ContainerAllocator>& v)
  {
    s << indent << "country: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.country);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LABA2_MESSAGE_WECREQUEST_H
